[template]
keys = [
  "/webapps",
  "/services"
]
mode = "0644"
src = "nginx-subliminl.tmpl"
dest = "/data/config/subliminl.conf"
#check_cmd  = "/usr/local/sbin/nginx -t -c {{ .src }}"
reload_cmd = "/reload.sh"
